spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamano
      sort:
        sort-parameter: orden
  flyway:
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true